CREATE TABLE TODOS ( 
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TODO TEXT NOT NULL,
    STATUS TEXT NOT NULL CHECK (STATUS IN ('pending', 'completed')) DEFAULT 'pending',
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);