CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,

    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);